- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    id: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn
    underwearb: ClothingUnderwearBottomBoxersWhite # AlphaCentauri-Underwear
  underweart: ClothingUnderwearTopBraWhite # AlphaCentauri-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # AlphaCentauri-Underwear

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn
